exp_name: mmnist
dataset: 'MMNIST'

batch_size: 256
num_workers: 4
drop_last: True
class_dim: 20
font_file: 'FreeSerif.ttf'
labels:

method: 'joint_elbos' # choose from 'joint_elbos', 'moe', 'poe'
method_mods:
  modality_jsd: False
  modality_poe: False
  modality_moe: False
  joint_elbo: False
  poe_unimodal_elbos: True
  factorized_representation: False
  include_prior_expert: False # is this the same as fac rep?

dir:
  data_path: './data/'
  clf_path: './trained_classifiers-20230327T173300Z-001/trained_classifiers/trained_clfs_mst'
  fid_path:
  inception_path: './pt_inception-2015-12-05-6726825d.pth'
    # MMNIST
  pretrained_clf_paths:
    - './trained_classifiers-20230327T173300Z-001/trained_classifiers/trained_clfs_polyMNIST/pretrained_img_to_digit_clf_m0'
    - './trained_classifiers-20230327T173300Z-001/trained_classifiers/trained_clfs_polyMNIST/pretrained_img_to_digit_clf_m1'
    - './trained_classifiers-20230327T173300Z-001/trained_classifiers/trained_clfs_polyMNIST/pretrained_img_to_digit_clf_m2'
    - './trained_classifiers-20230327T173300Z-001/trained_classifiers/trained_clfs_polyMNIST/pretrained_img_to_digit_clf_m3'
    - './trained_classifiers-20230327T173300Z-001/trained_classifiers/trained_clfs_polyMNIST/pretrained_img_to_digit_clf_m4'
  # MMNIST
unimodal_datapaths:
  train:
    - './data/MMNIST/train/m0/'
    - './data/MMNIST/train/m1/'
    - './data/MMNIST/train/m2/'
    - './data/MMNIST/train/m3/'
    - './data/MMNIST/train/m4/'
  test:
    - './data/MMNIST/test/m0/'
    - './data/MMNIST/test/m1/'
    - './data/MMNIST/test/m2/'
    - './data/MMNIST/test/m3/'
    - './data/MMNIST/test/m4/'

LR: 0.001
manual_seed: 1265
beta_values:
  beta: 2.5
  beta_1: 0.9
  beta_2: 0.999
  beta_style: 1.0
  beta_content: 1.0

div_weight:
  div_weight:
  div_weight_uniform_content:

evaluation:
  use_clf: True # should generate samples be classified (default=False)
  calc_nll: True # calculation of nll (default=False)
  eval_lr: True # can probably be done by lightning trainer (default=False)
  calc_prd: True # calculation of prec-rec for gen model (default=False)
  eval_freq: 25 # freq of eval of latent representation of generative performance (in # of epochs) | (default=10)
  eval_freq_fid: 100 # freq of eval of latent representation of generative performance (in # epochs) | (default=10)
  num_samples_fid: 10000 # numer of samples the calculation of fid is based on (default=10000)
  num_train_samples_lr: 500 # number of training samples to train the lr clf (default=500)
  save_figure: False # (default=False)
  subsampled_reconstruction: True # (default=True)

# data_dependent:
style_dim: 0
img_size_m1: 28
num_channels_m1: 1
img_size_m2: 32
num_channels_m2: 3
likelihood: 'laplace'
kl_annealing: 0

trainer_params:
  devices: 'auto'
  accelerator: 'gpu'
  max_epochs: 100

logging_params:
  save_dir: 'logs/'
  name: 'polyMnist'