data_params:
  data_path: "./data"
  batch_size: 256
  modality_1:
    mod_type: 'mnist'
    decoder: DecoderImg
    encoder: EncoderImg
    class_dim: 20
    style_dim:




exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "trimodVAE"