data_params:
  data_path: "./data"
  batch_size: 256
  class_dim: 20
  # add/remove modalities here
  modality_1:
    mod_type: 'mnist'
    # rest set a default
  modality_2:
    mod_type: 'svhn'
  modality_3:
    mod_type: 'text'




exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "trimodVAE"