data_params:
  directories:
    data_path: './data'
    clf_path: '../clf'
    fid_path: None
    inception_path: '../inception_state_dict.pth'
  batch_size: 256
  num_workers: 8
  class_dim: 20
  model: VAEtrimodalSVHNMNIST
  method: 'poe' # choose method for training the model
  method_mods:
    modality_jsd: False
    modality_poe: False
    modality_moe: False
    joint_elbo: False
    poe_unimodal_elbos: True
    factorized_representation: False
  font_file: 'FreeSerif.ttf'
  # add/remove modalities here
  modality_1:
    mod_type: 'mnist'
    # rest set a default
  modality_2:
    mod_type: 'svhn'
  modality_3:
    mod_type: 'text'

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265
  beta_values:
    beta: 0.5
    beta_1: 0.9
    beta_2: 0.999
    beta_style: 1.0
    beta_content: 1.0
    beta_m1_style: 1.0
    beta_m2_style: 1.0
    beta_m3_style: 1.0
  div_weight_m1_content: 0.25
  div_weight_m2_content: 0.25
  div_weight_m3_content: 0.25
  div_weight_uniform_content: 0.25
  evaluation:
    use_clf: False # should generates samples be classified
    calc_nll: False # calculation of nll
    eval_lr: False # can probably be done by lightning trainer
    calc_prd: False # calculation of prec-rec for gen model
    eval_freq: 10 # freq of eval of latent representation of generative performance (in # of epochs)
    eval_freq_fid: 10 # freq of eval of latent representation of generative performance (in # epochs)
    num_samples_fid: 10000 # numer of samples the calculation of fid is based on
    num_train_samples_lr: 500 # number of training samples to train the lr clf
  data_dependent:
    style_m1_dim: 0
    style_m2_dim: 0
    style_m3_dim: 0
    len_sequence: 8
    num_classes: 10 # number of classes on which the dataset trained
    dim: 64
    data_multi: 20 # number of pairs per sample
    num_hidden_layers: 1
    likelihood_m1: 'laplace' # output distribution
    likelihood_m2: 'laplace' # output distribution
    likelihood_m3: 'categorical' # output distribution

trainer_params:
  gpus: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VAEtrimodalSVHNMNIST"