exp_name: mst
dataset: 'SVHN_MNIST_text'

batch_size: 256
num_workers: 4
drop_last: true
class_dim: 20
font_file: 'FreeSerif.ttf'
labels:

method: 'joint_elbos' # options are 'joint_elbos', 'poe', 'moe'
method_mods:
  modality_jsd: false
  modality_poe: false
  modality_moe: false
  joint_elbo: false
  poe_unimodal_elbos: true
  factorized_representation: false

dir:
  data_path: './data/'
  clf_path: './trained_classifiers-20230327T173300Z-001/trained_classifiers/trained_clfs_mst/'
  fid_path: './None'
  inception_path: './pt_inception-2015-12-05-6726825d.pth'

modality_1:
  mod_type: 'mnist'
  encoder: 'IMG'
  encoder_save: 'encoderM1'
  decoder: 'IMG'
  decoder_save: 'decoderM1'
  likelihood: 'laplace'
  beta_style: 1.0
  div_weight: 0.25
  style_dim: 0
  clf_save: 'clf_m1'
modality_2:
  mod_type: 'svhn'
  encoder: 'SVHN'
  encoder_save: 'encoderM2'
  decoder: 'SVHN'
  decoder_save: 'decoderM2'
  likelihood: 'laplace'
  beta_style: 1.0
  div_weight: 0.25
  style_dim: 0
  clf_save: 'clf_m2'
modality_3:
  mod_type: 'text'
  encoder: 'Text'
  encoder_save: 'encoderM3'
  decoder: 'Text'
  decoder_save: 'decoderM3'
  likelihood: 'categorical'
  beta_style: 1.0
  div_weight: 0.25
  style_dim: 0
  clf_save: 'clf_m3'

LR: 0.001
manual_seed: 1265
beta_values:
  beta: 2.5
  beta_1: 0.9
  beta_2: 0.999
  beta_style: 1.0
  beta_content: 1.0

div_weight:
  # div_weight:
  div_weight_uniform_content: 0

evaluation:
  use_clf: True
  calc_nll: True
  eval_lr: True
  calc_prd: True
  eval_freq: 1
  eval_freq_fid: 1
  num_samples_fid: 10000
  num_train_samples_lr: 500
  save_figure: False

len_sequence: 8
num_classes: 10
dim: 64
data_multi: 20
num_hidden_layers: 1

trainer_params:
  devices: 'auto'
  accelerator: 'gpu'
  max_epochs: 100

logging_params:
  save_dir: 'logs/'
  name: 'svhn_mnist_text'
